spring.application.name=cadastro-usuario
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:mysql://localhost/cadastroUsuario
spring.datasource.username=root
spring.datasource.password=Enzo0509*